### ISSUE TITLE
electron-largetype

### ISSUE THREAD

**Issue by progrium** [sindresorhus/awesome-electron#180]
Not sure if this is awesome enough, so I'm submitting as an issue first:
https://github.com/progrium/electron-largetype

**Comment by sindresorhus** [comment]
Sure, looks useful, but note in https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md 

> If you just created something, wait at least a couple of weeks before submitting.

**Comment by progrium** [comment]
Hah, ok. Is that to make sure you reflect on what you made to see whether it is actually as cool as you thought when you made it?
