### ISSUE TITLE
Built on Electron pull request and order of featured applications

### ISSUE THREAD

**Issue by gautamsi** [sindresorhus/awesome-electron#229]
I have noticed people make pull request to add their icon on top of the row. I keep checking regularly on what's new on the list. It is difficult to keep track of icons getting here and there each time someone adding it. 

May I propose 
1.Featured Section: where only known developers like Microsoft Facebook and other big names can put pull request. Electron team can arrange them however you like. 
2.Other section: where it must be at the end and not in middle of lines.

it will make it easy for people like me to follow up on progress and community efforts.

**Comment by parro-it** [comment]
Contribution guidelines already contains a rule that state that new contribution must be appended at the end of a section

Regarding featured section, I think that could be difficult to maintain...

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/awesome-electron/commit/bbe010216684154d81f8a7d7089b65583bf898ca
