### ISSUE TITLE
Vivaldi is electron-based?

### ISSUE THREAD

**Issue by Tribex** [sindresorhus/awesome-electron#23]
I took a quick look at the inside of the Vivaldi deb file, and the file layout seems considerably different from electron's. The executable itself is tiny and libnode and such are missing.

Where exactly is it mentioned that Vivaldi is based on electron? Just wondering, as I'm sure we don't want to mislead people.

**Comment by sindresorhus** [comment]
I guess you're right. I should have used better sources:

http://stackoverflow.com/tags/atom-shell/info
http://www.meetup.com/Electron/pages/List_of_Products_Built_on_Atom_Shell/

**Comment by Tribex** [comment]
Alright, thanks a lot!
