### ISSUE TITLE
Any recommendations for GUI testing frameworks?

### ISSUE THREAD

**Issue by aluxian** [sindresorhus/awesome-electron#238]
So far, I've found these two:
- http://www.testplant.com/
- http://robotframework.org/

But I don't have any experience with them or desktop GUI testing frameworks in general. Does anyone test their Electron apps?

**Comment by z-ax** [comment]
Our team uses SikuliX.

**Comment by Aluxian** [comment]
Thanks, do you have it running on a CI? Is your app open source?

-- 
Alexandru Rosianu
Full-Stack Developer
aluxian.com | startersquad.com

On 15 April 2016 at 17:29:17, Dmytro (notifications@github.com) wrote:

Our team uses SikuliX.

**Comment by imlucas** [comment]
https://github.com/electron/spectron

Simple. Powerful. Works great.

**Comment by Aluxian** [comment]
@imlucas Do you know any open source apps using it? Or some examples? Thanks!

**Comment by Aluxian** [comment]
@imlucas which of the following is Spectron able to do? 

- unit tests 
- integration tests 
- functional/end-to-end tests

**Comment by imlucas** [comment]
@Aluxian spectron is for end-to-end tests (behind the scenes, it's using selenium).  

For unit and integration tests, we use https://github.com/jprichardson/electron-mocha

**Comment by Hiran91** [comment]
@imlucas  What is the best tool/framework to automate GUI on Visual Studio Code (VS Code)? Can you recommend good one?

**Comment by TetianaMalva** [comment]
> @imlucas What is the best tool/framework to automate GUI on Visual Studio Code (VS Code)? Can you recommend good one?

Cypress.
