### ISSUE TITLE
Add other electron maintainers

### ISSUE THREAD

**Issue by zeke** [sindresorhus/awesome-electron#250]
Hey @sindresorhus would you mind giving my colleagues @jlord and @kevinsawicki access to this repo, so they can help maintain as necessary?

I've added the four of us as owners of the npm package:

```
❯ npm owner ls awesome-electron
jlord <to.jlord@gmail.com>
kevinsawicki <kevinsawicki@gmail.com>
sindresorhus <sindresorhus@gmail.com>
zeke <zeke@sikelianos.com>
```

**Comment by sindresorhus** [comment]
Done :)
