### ISSUE TITLE
Package add suggestions

### ISSUE THREAD

**Issue by justinmchase** [sindresorhus/awesome-electron#33]
There are a few projects you may want to add to your list:

[electron-builder](https://npmjs.org/packages/electron-builder)
> Create installers for Windows and macos

[electron-updater](https://npmjs.org/packages/electron-updater)
> Cross-platform, js/npm based auto-updater

I'm working on the updater module. It would be nice to have community endorsement / contribution.

**Comment by sindresorhus** [comment]
Sure, can you do a PR?

https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md
