### ISSUE TITLE
LosslessCut - Simple tool for quick and lossless rough edits of raw videos

### ISSUE THREAD

**Issue by mifi** [sindresorhus/awesome-electron#375]
Nothing big, but i thought it might qualify. I just made this simple video editor for super quickly discarding useless parts from big raw video files from video cameras/drones etc without re-encoding. It's based on Electron and React and uses ffmpeg (not included) for the processing. I'm aware of the 20 day wait time, so I'll just put it here to maybe see if people find it useful.

https://github.com/mifi/lossless-cut

**Comment by sindresorhus** [comment]
Looks useful. I've created a new thread for people looking for feedback. Can you post here instead: https://github.com/sindresorhus/awesome-electron/issues/378 ;)
