### ISSUE TITLE
Removed Deprecated apps

### ISSUE THREAD

**Issue by anubhavsrivastava** [sindresorhus/awesome-electron#456]
We can remove deprecated apps for eg Anatine.

**Comment by sindresorhus** [comment]
Yes. Any other apps?

**Comment by anubhavsrivastava** [comment]
I will go through the entire list once.

**Comment by anubhavsrivastava** [comment]
Following are also deprecated.
soundcast - https://github.com/andresgottlieb/soundcast
cuttle - https://github.com/oakmac/cuttle

**Comment by sindresorhus** [comment]
> Do you see any point in specifying OS (win,max,linux) support for individual apps via some icon/badge?

Nah, not worth the work it takes to do the work and keep it updated.
