### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-electron#5]
Comment here if there's anything you wish existed to make it easier to create apps with Electron. Can be components, tools, docs, etc. Or any apps you wish existed.

Comment if you started working on any of the wishes.

**Comment by staygrimm** [comment]
I'd love to see a guide or a simple example on getting CI working

**Comment by sindresorhus** [comment]
@staygrimm Getting CI working how? Can you be more specific on what you're looking for?

**Comment by RangerMauve** [comment]
Bluetooth libraries that would work with it cross-platform would be amazing.

**Comment by staygrimm** [comment]
@sindresorhus Sorry I specifically mean the process of installing Electron on a provider such as Travis and running tests inside a headless Electron.   

I've found this repo: https://github.com/atom/ci but the process is somewhat convoluted, requiring the use of APM, atom package manager.  Also, CoffeeScript.  I'd really love to figure out how to get Travis working in a simpler manner, using only npm and perhaps @maxogden's modules.

**Comment by maxogden** [comment]
I got electron working headlessly on ubuntu here: https://github.com/moose-team/peerbot

i'm not sure travis would let you run `xvfb` though

**Comment by maxogden** [comment]
@RangerMauve you can use `noble` and `bleno` from npm with electron. they work in OSX and Linux. not sure what the windows story is

**Comment by RangerMauve** [comment]
@Maxogden yeah, I've been following both of those. The issue is that Windows is important for what I'm going to deploy. :'(

**Comment by maxogden** [comment]
@RangerMauve gotcha. unfortunately theres nothing special about electron that will make bluetooth on windows any easier to build, since it is just io.js under the hood. so if theres any hope of bluetooth in electron it would have to come from modules like bleno/noble

**Comment by RangerMauve** [comment]
@maxogden Yeah, I'm not well versed in Windows enough to do it myself yet, either. I was thinking that it might be possible to just cheese it and use an ffi library to call Windows APIs directly from JS. Alternately my hope is that it'll be [available in blink some day](https://github.com/WebBluetoothCG/web-bluetooth)

**Comment by floydpink** [comment]
Why is [the "official" boilerplate](http://swara-app.github.io/swara-server/) left out of the ones this list?

**Comment by sindresorhus** [comment]
@floydpink Wrong link?

**Comment by floydpink** [comment]
Yes, that was a copy-paste accident - had corrected it immediately though: https://github.com/atom/electron-starter

**Comment by msegundo** [comment]
Hi all, 
do you have browserSync working?. Or other great reloader o live edition like: Amok.js, WebStorm Live editing, Budo Chrome...

**Comment by sindresorhus** [comment]
@floydpink It's IMHO not a good starting point and it seems it's going to be changed a lot: https://github.com/sindresorhus/awesome-electron/pull/4#issuecomment-96404461

**Comment by szymonkaliski** [comment]
@msegundo I have live-reloading without compilation step! https://gist.github.com/szymonkaliski/0b33c6031ce5679dc608

Also working great with electron! :)

**Comment by sindresorhus** [comment]
@msegundo I think you can easily set up something like [`BrowserSync`](http://www.browsersync.io/). Electron is pretty much just a browser window.

// @shakyShane

**Comment by msegundo** [comment]
@sindresorhus and @szymonkaliski thanks guys. I'm trying to get browserSync working but Electron don't reload. Clean cache is a great idea but in my case I need also HTML and CSS injection.

This recipe working inside Electron will be awesome: https://github.com/Browsersync/recipes/tree/master/recipes/html.injection

**Comment by szymonkaliski** [comment]
@msegundo could you show us simplified version of code you're using? I don't have anything to share with you, but I remember I was able to set up browser-sync with electron pretty easily some time ago...?

**Comment by mattdesl** [comment]
@msegundo for simple page reloading and live CSS injection, you could use budo -- [example](https://gist.github.com/mattdesl/d904cb2c7235cfabdbea). Or webpack-dev-server, or just [watchify](https://github.com/substack/watchify) and chokidar directly.

**Comment by msegundo** [comment]
Thanks again @szymonkaliski. My problem is with the file protocol. My problem is with the file protocol. I don't want to use the server of browserSync to serve my files and I can't to configure the hostname properly and the connection between my app and browserSync can't be established.

**Comment by szymonkaliski** [comment]
@msegundo but you are using http server, right? Look into `proxy` option for browserSync, I usually have express server running, and then browserSync proxying for live reload functionality.

**Comment by msegundo** [comment]
@szymonkaliski that's the key, I am not using any http server. I am using the file protocol. Is a good practice to use a http server always?

**Comment by szymonkaliski** [comment]
@msegundo I really doubt if browserSync can work with *files* and not http data... Using http server for Electron is usually a bad idea, you can do CSS injection yourself with websockets and file watcher, I'm not sure about html injection but should be possible as well. But this will require some work, so if you are in a hurry maybe doing http sever for dev is not a bad idea. 
I also just stumbled upon this: https://github.com/Quramy/electron-connect

**Comment by msegundo** [comment]
@szymonkaliski We get BrowserSync working with http server but only for development. We agree with you. 

We are going to check electron-connect. Thanks a lot!

**Comment by TrevorJTClarke** [comment]
This list is great! I would suggest adding: https://github.com/paulcbetts/electron-compile

**Comment by hashd** [comment]
We're working on a cross platform writing tool called Marvelous. https://github.com/hashd/Marvelous

It's still work in progress and we should hopefully have our first release for all 3 platforms by this month end.

**Comment by brooksn** [comment]
I'd like to find snippets or discussion about achieving a native-feeling UI (esp. for OS X). For example, this [blog post about using an apple system font in the browser](http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/) isn't about electron, but I think it's relevant.

**Comment by NaveenKarippai** [comment]
Hello @sindresorhus ,
What do you think about including a space in the README for ongoing projects that could help beginners to collaborate on? It could help newbies to have a look at the code of starter projects and contribute.

**Comment by sindresorhus** [comment]
@NaveenKarippai Can you provde some examples of what that would be?

**Comment by NaveenKarippai** [comment]
@sindresorhus For example, I have a noob project prototype built on electron ![hybrid-weather](https://github.com/NaveenKarippai/hybrid-weather) and I think if there is a list of such projects it would be useful for developers to collaborate and learn. What do you think?

**Comment by sindresorhus** [comment]
I don't think a list is a good format for this. I instead opened an issue where people can post collaboration requests: https://github.com/sindresorhus/awesome-electron/issues/88

**Comment by NaveenKarippai** [comment]
@sindresorhus sounds good!

**Comment by sindresorhus** [comment]
##### Request

`electron-window-state` - Need a library for storing and loading window state as Electron does not save/restore window size and position between loads.

More here: https://github.com/sindresorhus/module-requests/issues/9 (discuss there)

**Comment by zz85** [comment]
Current Wish: Electron App Manager
(maybe somewhat related to #95 and https://github.com/atom/electron/issues/673)

Imho, Electron Apps are usually bloated because they package with their own node/chromium runtime (though I can understand why it is good at times). It is like an irony that SpaceRadar is about a hundred MB unzipped application for example. I think Chrome App approach can be pretty nice (you can download new apps pretty quickly).

So the proposition is do have an manager app somewhat along the lines of nvm/kitematic/brew. However, instead of downloading binaries, check out the git repository or source (which I believe to be much smaller than builds), and maintain a single update to date Electron binary responsible for running the apps. The app might have to install dependencies, rebuild native bindings etc but that would be in it's implementation.

Anyway just sharing this idea which is at the top of my head right now. Will be cool to know if someone is already working on this, otherwise I might attempt one when I have some time.

**Comment by sindresorhus** [comment]
@zz85 What if two apps require two different versions of Electron and neither work on the other ones version? It's a good idea in theory, but comes with a lot of complications. Electron is still in active development and its API has changed many times, even removing whole APIs at times. I think this would be more feasible when Electron turns 1.0.0.

I personally prefer the current approach. Everything is self-contained and just works. You never have to deal with dependency conflicts. Disk space is cheap today anyways, and an Electron app is 35 MB when compressed, so not that bad to download either.

**Comment by zz85** [comment]
@sindresorhus I agree that there would be complications. However what I'm proposing isn't intended to change the way Electron is but rather an automation for the way I'm testing Electron apps, which is checking out the code, installing dependencies less Electron, and running the app through my global Electron.

While self-containment is nice, perhaps I've a slightly different view as I'm stingy with my disk space (since SSD still isn't really cheap), and that I'm connected at times on mobile data (where I would prefer downloading KB of code rather than 35MB each time each app updates. unless we get chrome kind of binary diff updates, but that's a separate topic... : )

**Comment by kokarn** [comment]
I must say i agree with @sindresorhus.
I think of this as applications, not just webpages. In that case 35MB is
nothing and even 100 or 200 is still really nothing at all.

And even SSDs are getting cheaper all the time so i don't really see that
as a point worth anything anyways :P

**Comment by parro-it** [comment]
What I would prefer is to have a way - as a developer - to install electron apps without [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) local dependency, and run them through my global installed `electron-prebuilt`. 

That's beacuse when I install a node module (e.g. a command line tool) that require a node version I've not installed on my machine, npm doesn't install a new node version for it automatically, it just give me an advice: "you have to install node 5 for this to work". I would expect the same for an electron app: just give me an advice, I'll be able to solve the problem by myself... 

Instead, as an end user, maybe a not so experienced one, I would prefer to get a packaged app that already contains it's electron version. I will not care so much if the app weight 50Mb or 100Mb or 4Mb,
I care much that is easy to install and update.

**Comment by zz85** [comment]
Just wanted to mention that I've started on my wish with a very raw prototype https://github.com/zz85/electron-awesomeness - right now it is really simple but hopefully it gives a better idea on what I was thinking about. Feel free to try if it is useful and file any issues if necessary :)

![electron-awesomeness-2](https://cloud.githubusercontent.com/assets/314997/11072050/e9d7b73a-881e-11e5-9eda-e812fc3ade00.gif)

**Comment by Thrilleratplay** [comment]
I would like to see an offline JSFiddle/Codepen clone.  Preferably with preprocessors and the option to export to a local directory, Github Gist or repo.  It would be a good tool to teach webdevelopment

**Comment by ezekg** [comment]
@zz85, that's awesome.

**Comment by philfreo** [comment]
I'd love to see an example (code & UI) of an Electron app that has good find-on-page / on-page-search like Chrome does with cmd-f/ctrl-f. I saw in https://github.com/electron/electron/issues/2037 that it's not supported natively in Electron however that there are some [methods](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsfindinpagetext-options) that should help.

**Comment by winnchen** [comment]
I would like to enable page search(ctrl+f) in application.

**Comment by hasusuf** [comment]
+1

**Comment by dkniffin** [comment]
I'd _love_ to see an image editor built in electron. At the moment, I need something like inkscape (vector/svg editor), but something akin to gimp (raster/jpg/png editor) would also be cool. I know these are very complicated tools, but to be quite honest, the open source ones out there right now are crap.

**Comment by philfreo** [comment]
Here's a starting point for someone to implement find on page search: https://github.com/edulan/electron-search-example. Though I'd still like to see one that is closer to Chrome's UI.

**Comment by jenstornell** [comment]
Is there anything around a collapable file tree sidebar to start with? Similar to Windows and Mac file tree.
