### ISSUE TITLE
Awesomeness Check for Ao Electron App

### ISSUE THREAD

**Issue by novddd** [sindresorhus/awesome-electron#538]
Hey @sindresorhus ! Saw this electron app shared on Twitter by Ubuntu: https://twitter.com/ubuntu/status/996773537770860544
It's called Ao, and it is a client for Microsoft's Wunderlist successor, here is the link to the repo: https://github.com/klauscfhq/ao
Love your awesome list! Happy to contribute in any way!

**Comment by sindresorhus** [comment]
Closing in favor of #542
