### ISSUE TITLE
add Trilogy

### ISSUE THREAD

**Issue by ram-you** [sindresorhus/awesome-electron#548]
Hi,
please consider adding **Trilogy**:

> trilogy is a Promise-based layer over SQLite, featuring type-casting schema models and allowing both native & pure JavaScript backends ( and in-memory databases ).

https://github.com/citycide/trilogy

@citycide

**Comment by sindresorhus** [comment]
Looks useful! Do a PR to add it and follow the contribution guidelines ;)

**Comment by ram-you** [comment]
@citycide
