### ISSUE TITLE
share menu extension for macOS?

### ISSUE THREAD

**Issue by tessus** [sindresorhus/awesome-electron#573]
I'm wondering how to generate a share menu extension to share stuff with an Electron application.
Is this exclusively a macOS thing or are there any tools to make this happen?

**Comment by sindresorhus** [comment]
https://discuss.atom.io/c/electron is a better place to ask questions like that :)

**Comment by tessus** [comment]
Thanks for the info, but what has a user forum for an editor to do with share menu extensions?
