### ISSUE TITLE
Who is hiring?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-electron#612]
This issue is for companies looking for people with Electron experience. Both permanent positions and contract work welcome.

#### Companies

Please state the job location and include the keywords REMOTE, INTERNS and/or VISA when the corresponding sort of candidate is welcome. When remote work is not an option, include ONSITE. Don't forget to include contact information. Be succinct.

Please only post if you personally are part of the hiring company—no recruiting firms or job boards. Only one post per company. If it isn't a household name, explain what your company does.

Please make sure to remove your post when the job is no longer available.

#### Commenters

This is meant only for job postings, not discussions around the jobs or companies. The only allowed non-job-post comments are questions about job postings that could benefit others.

---

Subscribe to this issue if you're looking for Electron-related work.

**Comment by natasass** [comment]
Hi all, I'm Natalie from [Overflow](www.overflow.io)

We have an opening for **contract** work on the Electron side of the Overflow app. This is a **REMOTE** position, preferably in European or Asian timezones. 

**Overflow** is a desktop app which allows designers to create interactive user flow diagrams straight from their designs. Currently, we have integrations with the 3 most popular design tools (Sketch, XD and Figma).

For more information on the project(scope, timeframe, etc...) please email me at **nataliem at overflow.io**

**Comment by emilbayes** [comment]
Hi, I'm Emil and partner at @hyperdivision

At Hyperdivision we work with peer to peer technology and cryptography, to turn cutting-edge research into user friendly products. We're currently developing Heimdall, a collaboration tool for banks, exchanges and other high-security users. We need help with further developing the desktop application and integrate more of our research into product form. We need a developer, preferably with full-stack experience, but not strictly required, to work with us from our Copenhagen office (**ONSITE**) at Pier 47. If you are from outside of Denmark, we can assist with relocation. If you are from outside the EU, we can assist with work permit. (**VISA**) The job is **FULL-TIME**.

We are a highly experienced team of open-source developers and public speakers, and we love to teach and share our passion. You will be encouraged to develop small, maintainable modules though your work and publish them as open-source under your name and the Hyperdivision Github organisation. See some of our work on @hyperdivision, @sodium-friends, @mafintosh and my profile.

We would like to encourage all interested persons to apply regardless of gender, ethnicity, educational background or seniority. We value building a diverse workplace where all can feel welcome and grow intellectually and personally. We will judge candidates on their aptitude, potential, attitude and interests.

Please [submit you application though the Hub](https://thehub.dk/jobs/full-stack-developer-electron-finance-security). If you have further questions please inquire to Emil Bay, either by phone +45 42 955 144 (also Signal and SMS) or by email on emilbayes@hyperdivision.dk

(Full job ad: https://thehub.dk/jobs/full-stack-developer-electron-finance-security)

**Comment by jprichardson** [comment]
**Who**

Hi, I'm JP, CEO of [Exodus](https://www.exodus.io).

**What**

Exodus is a desktop app built on Electron to secure, manage, and trade a portfolio of cryptocurrencies. We also have a React Native mobile app: https://www.exodus.io/mobile

We have close to 4 million downloads and are growing fast. We'd love to have an engineer join our **REMOTE**-only team to improve our usage of Electron and contribute back to the Electron project.

**Apply**

Simply send an email to jobs@exodus.io with the subject "Electron Engineer - FIRSTNAME LASTNAME" and tell us a little more about yourself. Please include your Github link.

**Comment by mane87** [comment]
Hi all, I'm Manuel, CTO of [Timeular](http://www.timeular.com).

Timeular is a unique combination of hardware and software that helps you to **track**, **understand** and **improve** how you work.

You can check out our software [here](https://timeular.com/download/) and have a look at our open source work [here](https://github.com/timeular).

We are a **fully remote team** of 16 people working from five countries and are between 20 and 40 years old. 
You can work whenever you want but we’re accepting applications only from people living in a timezone somewhere starting from GMT-4 till GMT+2 (GMT-5 till GMT+1 in winter northern hemisphere).

To know more about our benefits and [**to apply please read on here**:](https://timeular.com/jobs/#frontend-developer)
