### ISSUE TITLE
Is there interest in Electron App built with Clojurescipt

### ISSUE THREAD

**Issue by ducky427** [sindresorhus/awesome-electron#7]
This is a great [example](https://github.com/oakmac/cuttle) of an app built with Clojurescript using Electron.

**Comment by sindresorhus** [comment]
added in https://github.com/sindresorhus/awesome-electron/commit/e3b3f836b1ce195935404a57a1e17d941d8b9da6

**Comment by ducky427** [comment]
Thank you!
