### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-electron#88]
Post here if you have a project you want to collaborate on with someone. Could be an idea, something unfinished, something you need help on, or maybe you just want to teach someone. Open source is over-saturated these days, so make sure to sell your idea/project, why people should care, and what you're looking for.

**Comment by NaveenKarippai** [comment]
Started an open source project built on *electron, AngularJS and Ionic framework*. The aim of this project is to help newbies learn hybrid technologies and build cross platform apps (desktop, mobile and web). Github repo : ![hybrid-weather](https://github.com/NaveenKarippai/hybrid-weather)

**Comment by sindresorhus** [comment]
@NaveenKarippai Include what you're looking for.

**Comment by NaveenKarippai** [comment]
updated! Thanks :+1:

**Comment by sindresorhus** [comment]
@NaveenKarippai I think it would help to open some specific issues on your repo with easy things people can help out with to get them started.

**Comment by YurySolovyov** [comment]
I wonder how feasible it is to write basic 2-panel file manager? I'm a bit tired of Total commander, and I use only a small subset of its features, at work I use Nautilus, and it is not that great either.

**Comment by ingorichter** [comment]
I was thinking about the same for a while now. There is nothing great on OSX either and I'm more than willing to get it going.

**Comment by YurySolovyov** [comment]
@ingorichter, awesome, I'll try to came up with something later this week and post link here.

**Comment by YurySolovyov** [comment]
@ingorichter Created [eion](https://github.com/YurySolovyov/eion), very raw ATM, mostly just boilerplate (couldn't get hot module reloading working, but there is plain F5 reloading working), but shows current dir contents, planning to work on it on weekend. Not to spam anymore: [gittter room](https://gitter.im/YurySolovyov/eion)

**Comment by FabioLolix** [comment]
In Apps/Open Source what is the difference between featured and other?

**Comment by CritFlaw** [comment]
Is there a discord server for electron? For obvious reasons, trying to search for one on Google isn't useful.

**Comment by bennyben112** [comment]
#626 #625

**Comment by bennyben112** [comment]
We are the hit of our own interrest
Chillcore emotions amsterdam. B. V.

**Comment by kashaiahyah85** [comment]
I've been having a genuinely good time helping out with what I can at @thamara's https://github.com/thamara/time-to-leave
