### ISSUE TITLE
Idea -- Extensible PDF/Document viewer based on Electron

### ISSUE THREAD

**Issue by rkpatel33** [sindresorhus/awesome-electron#94]
Not  sure if this is the write place for this, but just putting an idea on the table that I would love to see -- creating an extensible PDF viewer based on Electron, possibly forked from Atom Shell the way Nylas is doing for email.

The hard part of rendering PDFs is already handled nicely by PDF.js, so it would be a matter of integration it into the Electron framework.

**Comment by sindresorhus** [comment]
Can you also answer "why"? Why does this need to exist? What does extensible mean in this context?

**Comment by ewnd9** [comment]
I can think of extensions like popup translation of selected text or instant share quotes to twitter.

**Comment by oiledCode** [comment]
So basically what you are saying is that you would like to collaborate to a project that develop the idea above? It wouldn't be better / easier to start this project yourself and use this https://github.com/sindresorhus/awesome-electron/issues/88 to ask for collaboration?

**Comment by rkpatel33** [comment]
I think this would be an interesting projec because, as bad as they are, lots and lots of docments are still exchanged, distributed, and consumed as PDFs, and the existing PDF readers out there are not that great to pretty aweful from a UX perspective. Acrobat Reader is the free standard, but if you want to do much to make changes to the document or annotate it, you have to purchase Acrobat Pro.

Extensible in this context means simply a viewer for which you can write plugin/extension that may do things like allowing:

- markup
- translation
- collaboration on review
- analysis of content
- extraction of content
- easier navigation
- front end to access repositories of documents that at still distributred in PDFs

This was not supposed to be a call for help for myself as it's beyond my skills at this point. I more wanted to put it in the ether in case it resonated with someone with interest and the appropriate skills. 

If this was the wrong place for it, I apologize.

**Comment by sindresorhus** [comment]
@rkpatel33 Thanks for the explanation. I'm convinced. Let's keep this open and hope for someone that's interested in doing this ;)

**Comment by rkpatel33** [comment]
Awesome, thanks!

**Comment by yoshuawuyts** [comment]
If anyone wants to extend [vmd](https://github.com/yoshuawuyts/vmd) to support more document types / more features PRs are more than welcome :sparkles:

**Comment by nextlevelshit** [comment]
@rkpatel33 Your idea is exactly what my project at university is going to be. Extensable PDF Viewer +1

**Comment by asantos00** [comment]
I'm thinking about making it. My idea is like an "ebook Reader" which will obviously support PDF, but I also want a shelf view, something to add "notes" to files, take snippets and make small "resumes".

If anyone is interested, send me a message! @yoshuawuyts If it fits your project I'm available to contribute too

**Comment by yoshuawuyts** [comment]
@asantos00 having bookshelfs and notes might be slightly out of scope for `vmd`, but if you're looking to render all types of documents in Electron, having support for that in `vmd` would be grand!

**Comment by ewnd9** [comment]
@asantos00 you could also add `fb2` support via https://github.com/chitalka/reader

**Comment by rkpatel33** [comment]
@asantos00 That sounds pretty cool. FYI, this is my startup: https://www.docnavapp.com/

The core of the viewer is pdf.js and there is a lot of analysis of the PDF file that goes on on the backend in Python. I have considered making a true desktop version of this, it would solve a lot of problems for me, but it would require wrapping up the Python with it. Being able to make notes and take snippets would be awesome too.

**Comment by pendar747** [comment]
I think having an app that has both ability to view file system pdf files and files loaded from url + library + note/annotation and extensibility with plugins would be great.
Right now there are a lot of research apps like mendeley which lock you in and force you to upload all your files to their cloud, so it nice to have some open source effort

**Comment by bhanuc** [comment]
Not sure if it helps anyone but I had created a pdf.js based viewer in electron but I am not able to give it much time due to my other commitments. You can check it at http://logophile.github.io .

**Comment by asantos00** [comment]
Seems pretty cool. I'm having the same problem, I have a lot of ideas but
so little time to execute them, this PDF reader I talked about in this
thread is one of them.

If I have the time to start it I will probably contribute to your project
instead of creating mine from scratch, good job!

Are you thinking about doing some documentation?

Regards

*Alexandre Miguel Portela dos Santos*

*e-mail:*      alexandre.santozz@gmail.com
*tel:   *           (+351) 913429823
*skype: *       santosalexandre21
*website: *    http://alexandrempsantos.com


2016-09-30 11:25 GMT+01:00 Bhanu Pratap Chaudhary <notifications@github.com>
:

**Comment by parro-it** [comment]
:+1: The site is really nice @bhanuc (the github band on the corner is partially covered by the header by the way).

**Comment by bhanuc** [comment]
Thanks for the kind words. I was supposed to create a documentation but I
am not sure the direction it would go into.
The interface is kinda inspired by the web kindle reader ui which is an
easy application to follow.
For the website issue, if interested kindly open a pull request, otherwise
I can fix it.
I am really looking forward to any kind of help in the project.

**Comment by bhanuc** [comment]
@asantos00 @parro-it  Have updated the project and linked the dev documentation to the project. Looking for more constructive feedback or support in the project.

**Comment by jjkavalam** [comment]
@rkpatel33 When considering a PDF reader please include a good full text search function. The current search function on most PDF readers hardly match the powerful search functions we see on the web and elsewhere.

**Comment by SeynalKim** [comment]
this is what I need right now...

**Comment by virsam69** [comment]
https://github.com/sindresorhus/awesome-electron.git    pdf thread

**Comment by 70m43** [comment]
https://github.com/agentcooper/react-pdf-highlighter
