### ISSUE TITLE
Module Management / Polyrepo GUI

### ISSUE THREAD

**Issue by mattdesl** [sindresorhus/awesome-electron#95]
Lots of people are moving to more modular codebases, but the tooling hasn't yet caught up.

It would be great to have an Electron app for managing dozens or hundreds of modules of code. Some feature ideas:
- Viewing outstanding PRs/issues across many repos
- Batch processing and multi-module tasks:
  - transfer ownership, add collaborators
  - deprecation with message
  - renaming modules
  - updating dependencies and running tests
  - running various other shell tasks like [ghpages](https://github.com/mattdesl/ghpages)
- Tagging and organizing local modules; these could also be pushed into `package.json` so the changes are not just local
- Fuzzy search of your own modules
- Quickly cloning & forking other people's modules to make fixes
- Easy overview of stats like your most used dependencies or devDependencies
- Bulk linting and/or sanitizing modules; e.g. scanning readmes for 404 links

The core logic should be decoupled from the tool itself. @yoshuawuyts and @hughsk did a bit of tinkering here:
https://github.com/polyrepo

**Comment by sindresorhus** [comment]
:+1: This need to exist! :)

**Comment by yoshuawuyts** [comment]
I'm happy to churn out the tooling behind this; supporting a standalone cli + js api. What do you reckon should come after `polyrepo-update` ?

**Comment by hughsk** [comment]
Maybe I'll take a stab at a UI :) @yoshuawuyts Central Park Open Source Day next week?

**Comment by yoshuawuyts** [comment]
@hughsk :sparkles: yes! I'll probably be up in Sydney Tue - Fri so take your pick (':

**Comment by hughsk** [comment]
Swell! Let's do Wednesday :)

**Comment by ahmadnassri** [comment]
certainly needed, happy to pitch in as well.

**Comment by RnbWd** [comment]
I've been brainstorming something similar for months, it's why I'm following some of y'all on Twitter / Github. I haven't made much progress though... too many modules. Something like this would be very useful :)

The electron app could act as a proxy, organizer / automator / linter and ui for npm/Github. Just being able to know what modules are required in a file by hovering over a visual tree of your projects fs would be useful, local or installed by npm, or something in between... I can dream. But the automaton of project management seems like a necessary tool to build more complex tools, and we already have everything we need too - it just needs to be put into an electron app... with a nice UI and search engine that doesn't exist yet...
